version: '3.8'

services:
  n8n-docs-mcp:
    build: .
    container_name: n8n-docs-mcp
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - NODE_DB_PATH=/app/data/nodes-v2.db
      - MCP_LOG_LEVEL=info
    ports:
      - "3000:3000"  # Only needed if using HTTP mode
    command: node dist/index-v2.js
    restart: unless-stopped

  # HTTP mode (for remote access)
  n8n-docs-mcp-http:
    build: .
    container_name: n8n-docs-mcp-http
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=production
      - NODE_DB_PATH=/app/data/nodes-v2.db
      - MCP_LOG_LEVEL=info
      - MCP_PORT=3000
      - MCP_HOST=0.0.0.0
      - MCP_DOMAIN=${MCP_DOMAIN:-localhost}
      - MCP_AUTH_TOKEN=${MCP_AUTH_TOKEN}
      - MCP_CORS=true
    ports:
      - "3000:3000"
    command: node dist/index-http.js
    restart: unless-stopped
    profiles:
      - http

# Usage:
# Local mode: docker-compose up n8n-docs-mcp
# HTTP mode: docker-compose --profile http up n8n-docs-mcp-http